version: "3.8"

networks:
  actionhero-nw:
    driver: bridge

services:
  actionhero-redis:
    container_name: actionhero-redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - actionhero-nw
  actionhero-mysql:
    container_name: actionhero-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=actionhero-db
      - MYSQL_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
    networks:
      - actionhero-nw
